name: Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    test:
        environment: actions
        runs-on: ubuntu-latest
        env:
          ASTRO_DB_REMOTE_URL: ${{ vars.ASTRO_DB_REMOTE_URL }}
          ASTRO_DB_APP_TOKEN: ${{ secrets.ASTRO_DB_APP_TOKEN }}
        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/setup@v2
            - uses: actions/setup-node@v7
              with:
                  node-version-file: ".nvmrc"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - run: pnpm exec playwright install --with-deps
            - run: pnpm run test
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 3
